services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
      target: development
    ports:
      - '3001:3000'
    env_file:
      - .env
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - .:/app
      - /app/node_modules
    command: sh -c "npx prisma migrate deploy && npm run start:dev"

  db:
    image: postgres:16-alpine
    ports:
      - '5433:5432'
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=auction_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U postgres -d auction_db || exit 1']
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
    name: auction_api_postgres_data
