name: Deploy Frontend to EC2 with Docker

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy Frontend
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Docker
        uses: docker/setup-buildx-action@v2

      - name: Build Docker Image
        run: |
          docker build -t frontend-app .

      - name: Save Docker Image
        run: |
          docker save frontend-app > frontend-app.tar

      - name: Deploy to EC2
        env:
          SSH_PRIVATE_KEY: ${{ secrets.EC2_SSH_PRIVATE_KEY }}
          EC2_HOST: ${{ secrets.EC2_HOST }}
          EC2_USER: ${{ secrets.EC2_USER }}
        run: |
          echo "$SSH_PRIVATE_KEY" > ssh_key
          chmod 600 ssh_key

          scp -i ssh_key frontend-app.tar $EC2_USER@$EC2_HOST:/tmp/frontend-app.tar

          ssh -i ssh_key $EC2_USER@$EC2_HOST << EOF
            docker load < /tmp/frontend-app.tar
            docker stop frontend-container || true
            docker rm frontend-container || true
            docker run -d -p 3002:3002 --name frontend-container frontend-app
          EOF

          rm ssh_key
